/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/algorithm-diagram': RouteRecordInfo<'/posts/algorithm/algorithm-diagram', '/posts/algorithm/algorithm-diagram', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/binary-search': RouteRecordInfo<'/posts/algorithm/binary-search', '/posts/algorithm/binary-search', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/Dijkstras-algorithm': RouteRecordInfo<'/posts/algorithm/Dijkstras-algorithm', '/posts/algorithm/Dijkstras-algorithm', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/double_pointer': RouteRecordInfo<'/posts/algorithm/double_pointer', '/posts/algorithm/double_pointer', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/dynamic-programming': RouteRecordInfo<'/posts/algorithm/dynamic-programming', '/posts/algorithm/dynamic-programming', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/greedy-alogrithm': RouteRecordInfo<'/posts/algorithm/greedy-alogrithm', '/posts/algorithm/greedy-alogrithm', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/hash-table': RouteRecordInfo<'/posts/algorithm/hash-table', '/posts/algorithm/hash-table', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/k-nearest-neighbor': RouteRecordInfo<'/posts/algorithm/k-nearest-neighbor', '/posts/algorithm/k-nearest-neighbor', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/large-o-notation': RouteRecordInfo<'/posts/algorithm/large-o-notation', '/posts/algorithm/large-o-notation', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/linear-programming': RouteRecordInfo<'/posts/algorithm/linear-programming', '/posts/algorithm/linear-programming', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/preferential-traversal': RouteRecordInfo<'/posts/algorithm/preferential-traversal', '/posts/algorithm/preferential-traversal', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/quick-sort': RouteRecordInfo<'/posts/algorithm/quick-sort', '/posts/algorithm/quick-sort', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/recursion': RouteRecordInfo<'/posts/algorithm/recursion', '/posts/algorithm/recursion', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/select-sort': RouteRecordInfo<'/posts/algorithm/select-sort', '/posts/algorithm/select-sort', Record<never, never>, Record<never, never>>,
    '/posts/algorithm/sort': RouteRecordInfo<'/posts/algorithm/sort', '/posts/algorithm/sort', Record<never, never>, Record<never, never>>,
    '/posts/browse/browsers-rendering': RouteRecordInfo<'/posts/browse/browsers-rendering', '/posts/browse/browsers-rendering', Record<never, never>, Record<never, never>>,
    '/posts/browse/how-browsers-work': RouteRecordInfo<'/posts/browse/how-browsers-work', '/posts/browse/how-browsers-work', Record<never, never>, Record<never, never>>,
    '/posts/browse/implementation-mechanism': RouteRecordInfo<'/posts/browse/implementation-mechanism', '/posts/browse/implementation-mechanism', Record<never, never>, Record<never, never>>,
    '/posts/browse/page': RouteRecordInfo<'/posts/browse/page', '/posts/browse/page', Record<never, never>, Record<never, never>>,
  }
}
