FROM python:3.9.7-slim-buster

COPY app.py /src/app.py

RUN pip install flask

WORKDIR /src
ENV FLASK=app.py


EXPOSE 5000

CMD ["flask", "run","-h","0.0.0.0"]

# docker image build -t flask-demo .
# docker run -p 5000:5000 flask-demo
